# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests to 10
    open-pull-requests-limit: 10
    # Assign pull requests to the repository owner
    assignees:
      - "jasonmcalpin"
    # Apply security label to easily identify security updates
    labels:
      - "security"
      - "dependencies"
    # Set versioning strategy to maintain compatibility
    versioning-strategy: "widen"
    # Limit updates to minor and patch versions
    commit-message:
      prefix: "deps"
      include: "scope"
    # Specify update constraints
    allow:
      - dependency-type: "direct"
    # Prevent updates to versions with known compatibility issues
    ignore:
      # Prevent react-helmet-async from updating to versions incompatible with React
      - dependency-name: "react-helmet-async"
        versions: [">=3.0.0"]
      # Keep React versions compatible with other dependencies
      - dependency-name: "react"
        versions: [">=19.0.0"]
      - dependency-name: "react-dom"
        versions: [">=19.0.0"]
      # Prevent major version updates for all packages (only allow minor and patch)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group related packages to ensure they're updated together
    groups:
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "react-helmet-async"
          - "react-router*"
          - "react-redux"
          - "@reduxjs/*"
      syntax-highlighting:
        patterns:
          - "prism-react-renderer"
          - "prismjs"
          - "refractor"
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "*eslint*"
          - "jest*"
          - "@testing-library/*"
      ui-libraries:
        patterns:
          - "framer-motion"
          - "@tailwindcss/*"
          - "tailwindcss"
