# Dependabot configuration file
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests to 10
    open-pull-requests-limit: 10
    # Assign pull requests to the repository owner
    assignees:
      - "jasonmcalpin"
    # Apply security label to easily identify security updates
    labels:
      - "security"
      - "dependencies"
    # Set versioning strategy
    versioning-strategy: auto
    # Group all minor and patch updates together
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "*eslint*"
          - "jest*"
          - "@testing-library/*"
      production-dependencies:
        patterns:
          - "react*"
          - "@reduxjs/*"
          - "framer-motion"
